import 'package:flutter/material.dart';

ImageProvider<Object> imageArmors = AssetImage('assets/images/mobile/background_armors.webp');
ImageProvider<Object> imageBackpack = AssetImage('assets/images/mobile/background_backpack.webp');
ImageProvider<Object> imageBooks = AssetImage('assets/images/mobile/background_books.webp');
ImageProvider<Object> imageCamping = AssetImage('assets/images/mobile/background_camping.webp');
ImageProvider<Object> imageDice = AssetImage('assets/images/mobile/background_create_character.webp');
ImageProvider<Object> imageFight = AssetImage('assets/images/mobile/background_fight.webp');
ImageProvider<Object> imageMain = AssetImage('assets/images/mobile/background_main.webp');
ImageProvider<Object> imageObjects = AssetImage('assets/images/mobile/background_objects.webp');
ImageProvider<Object> imagePotions = AssetImage('assets/images/mobile/background_potion.webp');
ImageProvider<Object> imagePouch = AssetImage('assets/images/mobile/background_pouch.webp');
ImageProvider<Object> imageSkills = AssetImage('assets/images/mobile/background_skills.webp');
ImageProvider<Object> imageStatistics = AssetImage('assets/images/mobile/background_statistics.webp');
ImageProvider<Object> imageTreasures = AssetImage('assets/images/mobile/background_treasures.webp');
ImageProvider<Object> imageWeapons = AssetImage('assets/images/mobile/background_weapons.webp');
ImageProvider<Object> imageCharacters = AssetImage('assets/images/mobile/background_characters.webp');
ImageProvider<Object> imageAdventures = AssetImage('assets/images/mobile/background_adventures.webp');
ImageProvider<Object> imageAdventuresSolo = AssetImage('assets/images/mobile/background_adventures_solo.webp');
ImageProvider<Object> imageWeb = AssetImage('assets/images/web/background.webp');
